# permissions for end users to edit visitorsapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: visitorsapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpmf-operator
    app.kubernetes.io/part-of: bpmf-operator
    app.kubernetes.io/managed-by: kustomize
  name: visitorsapp-editor-role
rules:
- apiGroups:
  - webapp.bpmf.io
  resources:
  - visitorsapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.bpmf.io
  resources:
  - visitorsapps/status
  verbs:
  - get
